Include stacktrace in incomplete filter
badoo/marathon pull request #15
Opened 2021-01-07 14:51 UTC by lukaville

Previously crash filter option only included crash events from LogCat, now it includes stacktrace of test failure as well.

2021-01-07 15:31 UTC, jeksor approved these changes

2021-01-08 12:26 UTC, yakimant requested changes
I guess `ignoreCrashRegexes` shall be renamed everywhere, but not sure. Please check.
That's my first review, don't know the code much.

2021-01-08 12:26 UTC, yakimant commented on core/src/main/kotlin/com/malinskiy/marathon/execution/Configuration.kt
> +            ignoreFailureRegexes = ignoreCrashRegexes ?: emptyList(),
```suggestion
            ignoreFailureRegexes = ignoreFailureRegexes ?: emptyList(),
```

2021-01-08 12:26 UTC, yakimant commented on marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/ConfigurationFactory.kt
> +    ignoreCrashRegexes = extensionConfig.ignoreFailureRegexes?.map { it.toRegex(RegexOption.DOT_MATCHES_ALL) },
```suggestion
    ignoreFailureRegexes = extensionConfig.ignoreFailureRegexes?.map { it.toRegex(RegexOption.DOT_MATCHES_ALL) },
```

2021-01-08 12:27 UTC, lukaville commented on core/src/main/kotlin/com/malinskiy/marathon/execution/Configuration.kt
> +            ignoreFailureRegexes = ignoreCrashRegexes ?: emptyList(),
Yes, I missed these ones, will update
Thanks!

2021-01-08 12:33 UTC, yakimant approved these changes

2021-01-08 12:33 UTC, merged